server:
  port: 8080
  servlet:
    context-path: /community

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nowcoder_community?useUnicode=true&characterEncoding
      =utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.sina.com
    port: 465
    username: ponnylv@sina.com
    password: 66a1aaab661fafab
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印日志(SQL语句)
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml

community:
  path:
    domain: http://localhost:8080